mysite/article/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='article'
urlpatterns = [
    path('', views.create_article, name="create_article"),
    path('view_all/', views.view_article, name="view_article"),
    re_path('view_all/(?P<title>.*)/', views.single, name = 'article_single')


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('dataset.urls')),
    path('chat/', include('chatapp.urls')),
    path('category/', include('category.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from category.models import Category
# Create your models here.

User = get_user_model()

class Editor(models.Model):
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    article_data = RichTextField(null=True, blank=True)
    category_selected = models.ManyToManyField(Category)
    project_link = models.CharField(max_length=200, null=True, blank=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    comment_desc = models.TextField(null=False, blank=False)
    article_id = models.ForeignKey(Editor, on_delete=models.CASCADE)

mysite/article/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Editor, Comment
User = get_user_model()

class ArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Title'}))

    class Meta:
        model = Editor
        fields = ['title', 'category_selected','article_data','project_link',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_desc']

mysite/article/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect
from .forms import ArticleForm, CommentForm
from .models import Editor, Comment
from datetime import datetime
# Create your views here.
@login_required(redirect_field_name='next')
def create_article(request):
    form = ArticleForm(request.POST or None)
    obj = Editor.objects.all()


    if form.is_valid():
        form.instance.username = request.user
        form.save()
        return HttpResponseRedirect('view_all/')

    return render(request,'article/yo.html',{'form':form, 'obj':obj})

def view_article(request):
    obj = Editor.objects.all()
    return render(request, 'article/view.html',{'obj':obj})

@login_required(redirect_field_name='next')
def single(request, title):
    try:
        obj = Editor.objects.get(title = title)
    except:
        return HttpResponseRedirect('/')
    form = CommentForm(request.POST or None)

    if form.is_valid():

        form.save(commit=False)
        form.instance.username = request.user
        form.instance.article_id = obj
        form.save()
        form = CommentForm()

    obj_com = Comment.objects.filter(article_id = obj)
    return render(request, 'article/single.html', {'obj': obj, 'form':form, 'obj_com':obj_com})

mysite/templates/article/single.html
{% extends 'base.html' %}
<div class="container">

{% block addcss %}
<style>
.heading{
     font-size: 50px;
    font-family: 'Arvo';

}
.cate{
    color: #6c757d;
}
.comment{
    border-width: 1px;
    border-color: #fe8d26;
    border-style: solid;
    border-radius: 5px;
    background: #d0701e14;
    margin: 10px;
}
.text{
margin:10px;

}

#id_comment_desc{
border-radius:10px !important;
max-height:200px;
}

</style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="heading">
            {{obj.title}}
        </div>
        <hr>
        <div class="cate">
            Categories :
            {% for cat in  obj.category_selected.all %}
            {{cat.category_name}},
            {% endfor %}
            <br>
            {{obj.username}}
        </div>
        <hr>
        <div>
            {{obj.article_data|safe}}
        </div>
        <hr>
        <div class="row">
          <div class="col">Write Comments</div>
          <div class="col-9">
            <form method="POST" action="">{% csrf_token %}
              <div class="w-100">
                {{form.comment_desc}}
              </div>
              <br>
              <button type="submit" class="btn btn-success">Add Comment</button>
            </form>
          </div>
        </div>
        {% for obj in obj_com  %}
            <div class="comment">
                <div class="text">
                    <font size="1px"> {{obj.username}} </font>
                    <br>
                    {{obj.comment_desc}}
                </div>
            </div>
        {% endfor %}
    </div>
  <script type="text/javascript">
    document.getElementById("id_comment_desc").classList.add("w-100")
  </script>
{% endblock %}

mysite/templates/article/view.html
{% extends 'base.html' %}
{% block addcss %}
<style>
.incard{
     margin: 15px;
     border-radius: 10px;
     color: white;
     background: #373737;
     font-size: 1vw;
     text-overflow: ellipsis;
}
.incard:hover{
    box-shadow: 0 .5rem 1rem rgba(100,0,0,.200)!important;
}
.text{
margin:10px;

}

.a{
color:white !important;

}
.a:hover{
color:#ff8d27 !important;
}
</style>
{% endblock %}

{% block content %}
    <div class="container" style="margin-top:10px;">
        <div class="row">
            {% for i in obj %}
                <div class="col-md-4 col-sm-6" >
                  <div class="incard">
                    <div class="text">
                      <font size="1px"> {{i.username}}</font><br>
                      <a href="{{i.title}}" class="a">
                        <font size="5px">
                          <div style=" font-size: 1vw;">
                            <b>{{i.title}}</b>
                          </div>
                        </font>
                        <hr>
                      </a>
                      <font size="1px"> {{i.timestamp}}</font>
                    </div>
                  </div>
                </div>
            {% endfor %}
        </div>
        <div style="position:fixed;top:50%;right:1%">
          <a href="/article" class="btn btn-success">Post Article</a>
        </div>
    </div>
{% endblock %}

mysite/templates/article/yo.html
{% extends 'base.html' %}
{% block addcss %}
<style>
#id_title{
    border-bottom-color: black;
    border-top: none;
    border-left: none;
    border-right: none;
    border-collapse: collapse;
}


.formd{
    border:none;
}
.cke_top {
    border-bottom: none !important;
    background : #ffbd82 !important;
    padding: 6px 8px 2px;
    white-space: normal;
}
.cke_bottom {
    padding: 6px 8px 2px;
    position: relative;
    border-top: 1px solid #d1d1d1;
    background: #f8f8f8;
    display: none !important;
}

body.cke_editable {

    border:none !important;
    cursor: text;

}

a.cke_button_off:hover, a.cke_button_off:focus, a.cke_button_off:active {
    background: #ffbd82 !important;
    border: 1px #211f1f solid;
    padding: 3px 5px;

}

#id_category_selected {
    color: #5c81a4;
    background: antiquewhite;
    text-align: center;
    height:300px;
    overflow: hidden;
    width:max-content;
    margin:auto;
}

#id_category_selected:hover{
    height:400px;
    background: antiquewhite;
    text-align: center;
    transform: scale(1.1);
    transition: all .3s;

}

.btn-sub{
    position: absolute;
    right: -100px;
    top: 50%;
     border-radius: 50%;
}



.btn-blink{
    background: yellow;
    animation: blinks .9s infinite;
}

@keyframes blinks{
    50% {background: red;}
}

</style>
{% endblock %}
{% block content %}

<br>
<br>
<div class="container">
  <div class="card shadow">
    <form method="POST" id="myFormID" action="">{% csrf_token %}
      {{form.media}}
      <br>
      <div class="float-right ">
        <div class="form-group" style="padding:20px;">
            {{form.title}}
        </div>
        <br>
        <div class="form-group" style="height:400px;">
            {{form.category_selected}}
        </div>
      </div>
      <div style="padding:10px;">
        {{form.article_data}}<br>
      </div>
      <div>
        <button type="submit" class="btn-sub btn btn-warning" style="color:white">Blog <i class="fa fa-paper-plane fa-lg"  aria-hidden="true"></i></button>
      </div>
    </form>
  </div>
</div>
<br><br>

<script>
    document.getElementById("id_category_selected").classList.add("form-control")

</script>
{% endblock %}